using Meridian.Client;
using Meridian.Client.Services;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");
var apiUrl = builder.HostEnvironment.BaseAddress;
builder.Services.AddScoped(_ => new HttpClient(new SessionMessageHandler { InnerHandler = new HttpClientHandler() }) { BaseAddress = new Uri(apiUrl) });
builder.Services.AddAuthorizationCore(o => o.AddPolicy("QuizAuthor", p => p.RequireRole("QuizAuthor", "Admin")));
builder.Services.AddScoped<LocalAuthenticationStateProvider>();
builder.Services.AddScoped<AuthenticationStateProvider>(sp => sp.GetRequiredService<LocalAuthenticationStateProvider>());
builder.Services.AddScoped<LocalAccountService>();
builder.Services.AddScoped<MeridianApiClient>();
builder.Services.AddScoped<SurveyService>();
builder.Services.AddScoped<UserApiClient>();
await builder.Build().RunAsync();
